import "./globals.css";
import { Poppins } from "next/font/google";

import QueryWrapper from "./components/wrapper/query-wrapper";

const poppins = Poppins({ weight: "400", style: "normal", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryWrapper>
        <body className={poppins.className}>{children}</body>
      </QueryWrapper>
    </html>
  );
}
